---
- name: Update package cache (Amazon Linux)
  yum:
    update_cache: yes

- name: Install prerequisites
  yum:
    name: "{{ docker_prerequisites }}"
    state: present

- name: Install Docker
  yum:
    name: docker
    state: present
