---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  
- include_tasks: install-docker.yml
- include_tasks: configure-docker.yml
- include_tasks: security-setup.yml