apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: todo-app
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - name: mongo
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: todolist
        resources:
          requests:
            memory: "128Mi" # Reduced from 256Mi
            cpu: "100m" # Reduced from 250m
          limits:
            memory: "256Mi" # Reduced from 512Mi
            cpu: "200m" # Reduced from 500m
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 120 # Increased delay
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mongosh
            - --quiet
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 90 # Increased delay
          timeoutSeconds: 10
          periodSeconds: 20
          failureThreshold: 3
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---

