apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
  labels:
    app: todo-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      # Add init container to wait for MongoDB
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.35
        command: [ 'sh', '-c', 'until nc -z mongo-service 27017; do echo waiting for mongo; sleep 2; done;' ]
      containers:
      - name: todo-app
        image: joisyousef/todo-app:latest
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: mongoDbUrl
          value: "mongodb://mongo-service:27017/todolist"
        - name: PORT
          value: "4000"
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 60 # Increased delay
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 30 # Increased delay
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi" # Reduced
            cpu: "50m" # Reduced
          limits:
            memory: "256Mi" # Reduced
            cpu: "200m" # Reduced
      imagePullSecrets:
      - name: docker-registry-secret
---
# Todo App Service
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
spec:
  selector:
    app: todo-app
  ports:
  - name: http
    port: 80
    targetPort: 4000
  type: ClusterIP
---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: todo-app-nodeport
  namespace: todo-app
spec:
  selector:
    app: todo-app
  ports:
  - name: http
    port: 80
    targetPort: 4000
    nodePort: 30000
  type: NodePort
