# playbooks/site.yml
---
- name: Configure VM and Install Docker on Amazon Linux
  hosts: web_servers
  become: yes
  gather_facts: yes

  tasks:
    - name: Update yum package cache
      yum:
        update_cache: yes

    - name: Install packages
      yum:
        name:
          - docker
          - git
          - htop
          - vim
          - python3-pip
        state: present

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose plugin
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        owner: root
        group: root

    - name: Ensure docker-compose is executable
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Symlink docker-compose into PATH
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
