---
- name: Install Docker and Docker Compose
  hosts: web_servers
  become: yes
  gather_facts: true

  vars:
    docker_compose_version: "2.21.0"

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present
      tags: docker

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
      tags: docker

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      tags: docker

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      tags: compose

    - name: Create symlink for docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
      tags: compose

    - name: Print Docker and Docker Compose version
      shell: |
        docker --version
        docker-compose --version
      register: docker_versions

    - name: Show installed versions
      debug:
        var: docker_versions.stdout_lines
