apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-app=joisyousef/todo-app:latest
    argocd-image-updater.argoproj.io/todo-app.update-strategy: latest
    argocd-image-updater.argoproj.io/todo-app.pull-secret: pullsecret:todo-app/docker-registry-secret
spec:
  project: default
  source:
    repoURL: https://github.com/joisyousef/Todo-List-nodejs.git
    targetRevision: HEAD
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
